project_id = "wwgmfrtiexjfhjoaifnr"

[functions.portfolio-chat]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.kirvano-webhook]
verify_jwt = false

[functions.cancel-kirvano-subscription]
verify_jwt = false

[functions.downgrade-to-free]
verify_jwt = false

