project_id = "wwgmfrtiexjfhjoaifnr"

[functions.portfolio-chat]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.cancel-mp-subscription]
verify_jwt = false

[functions.create-mp-subscription]
verify_jwt = false

[functions.get-mp-payments]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false
