project_id = "wwgmfrtiexjfhjoaifnr"

[functions.portfolio-chat]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.cancel-cakto-subscription]
verify_jwt = false

[functions.delete-user-admin]
verify_jwt = false

[functions.send-verification-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false


